name: glacier
description: Glacier media browser (Android)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Storage / paths
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  video_thumbnail: ^0.5.3

  # Picking files/folders
  file_picker: ^8.3.7

  # Crypto / utils
  crypto: ^3.0.5
  collection: ^1.18.0

  # Media playback (IMPORTANT)
  media_kit: ^1.1.11
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.5
  video_player: ^2.9.2

  # Device orientation handling
  native_device_orientation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
